// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOYW1bJKYojC3O9APRC5wJgdhlJ-5uK4',
    appId: '1:745252249351:web:49ca306fd9d0c0ac066fa2',
    messagingSenderId: '745252249351',
    projectId: 'mobileservicesapp-52f0a',
    authDomain: 'mobileservicesapp-52f0a.firebaseapp.com',
    storageBucket: 'mobileservicesapp-52f0a.appspot.com',
    measurementId: 'G-LWDJ36HXFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOtzKLVW64RcXvQoxLuG6zLof18625rn0',
    appId: '1:745252249351:android:0e7bf0821bf6376f066fa2',
    messagingSenderId: '745252249351',
    projectId: 'mobileservicesapp-52f0a',
    storageBucket: 'mobileservicesapp-52f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrn_7chMwVvqqhPX09waMEuoa9WtrJfW8',
    appId: '1:745252249351:ios:42238300eabd892d066fa2',
    messagingSenderId: '745252249351',
    projectId: 'mobileservicesapp-52f0a',
    storageBucket: 'mobileservicesapp-52f0a.appspot.com',
    iosBundleId: 'com.example.mobileservicesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrn_7chMwVvqqhPX09waMEuoa9WtrJfW8',
    appId: '1:745252249351:ios:42238300eabd892d066fa2',
    messagingSenderId: '745252249351',
    projectId: 'mobileservicesapp-52f0a',
    storageBucket: 'mobileservicesapp-52f0a.appspot.com',
    iosBundleId: 'com.example.mobileservicesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClOYW1bJKYojC3O9APRC5wJgdhlJ-5uK4',
    appId: '1:745252249351:web:2b5e68f87f4c0234066fa2',
    messagingSenderId: '745252249351',
    projectId: 'mobileservicesapp-52f0a',
    authDomain: 'mobileservicesapp-52f0a.firebaseapp.com',
    storageBucket: 'mobileservicesapp-52f0a.appspot.com',
    measurementId: 'G-CS121G6CC8',
  );
}
